#cloud-config
# -*- YAML -*-
# write_files:
#   - content: |
#       server {
#         listen 80;
#         server_name myvm.localhost;
#         return 302 https://$server_name$request_uri;
#          location / {
#             proxy_pass http://127.0.0.1:5000;
#             proxy_set_header X-Real-IP $remote_addr;
#         }
#       }
#     path: /etc/nginx/sites-available/default
runcmd:
  - |
    yum update -y 1>/bin/null
    amazon-linux-extras install nginx1 -y
  - |
    systemctl daemon-reload
    systemctl enable nginx
    systemctl start nginx